# Generated by Django 5.1.6 on 2025-02-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('FARMER', 'Farmer'), ('AGENT', 'Agent'), ('STAFF', 'Staff Member')], default='STAFF', max_length=10),
        ),
        migrations.AlterModelTable(
            name='user',
            table='authentication_user',
        ),
    ]
