# Generated by Django 5.1.6 on 2025-02-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
                ('farm_size', models.FloatField(help_text='Farm size in hectares')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
