# Generated by Django 3.2.8

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='ndvi_value',
            field=models.FloatField(blank=True, help_text='Latest Normalized Difference Vegetation Index', null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='rainfall_anomaly_mm',
            field=models.FloatField(blank=True, help_text='Rainfall deviation from historical average (mm)', null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='last_climate_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ] 