# Generated by Django 5.2 on 2025-04-21 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_add_geo_climate_fields'),
        ('farmers', '0002_farmer_updated_at_alter_farmer_farm_size_and_more'),
    ]

    operations = [
    ]
