# Generated by Django 5.2 on 2025-04-21 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_merge_20250421_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ndvi_value', models.FloatField(blank=True, help_text='NDVI value for this date', null=True)),
                ('rainfall_anomaly_mm', models.FloatField(blank=True, help_text='Rainfall anomaly in mm for this date', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about special weather events', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_history', to='farmers.farmer')),
            ],
            options={
                'verbose_name_plural': 'Climate histories',
                'ordering': ['-date'],
                'unique_together': {('farmer', 'date')},
            },
        ),
    ]
