# Generated by Django 5.1.6 on 2025-02-19 03:35

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate as a percentage', max_digits=5)),
                ('duration_days', models.IntegerField(help_text='Loan duration in days')),
                ('is_active', models.BooleanField(default=True)),
                ('requirements', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('DISBURSED', 'Disbursed'), ('ACTIVE', 'Active'), ('OVERDUE', 'Overdue'), ('PAID', 'Paid'), ('DEFAULTED', 'Defaulted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('disbursement_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('disbursement_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('credit_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('momo_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='farmers.farmer')),
                ('loan_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.loanproduct')),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_reference', models.CharField(max_length=100)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='loans.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('DISBURSEMENT', 'Loan Disbursement'), ('REPAYMENT', 'Loan Repayment')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('financial_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loans.loan')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_type', 'status'], name='loans_trans_transac_7ee9b3_idx')],
            },
        ),
    ]
