# Generated by Django 5.1.6 on 2025-03-14 23:15

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
                ('business_type', models.CharField(choices=[('SEEDS', 'Seeds Supplier'), ('FERTILIZER', 'Fertilizer Supplier'), ('EQUIPMENT', 'Farm Equipment'), ('GENERAL', 'General Agri-Inputs')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate as a percentage', max_digits=5)),
                ('duration_days', models.IntegerField(help_text='Loan duration in days')),
                ('is_active', models.BooleanField(default=True)),
                ('requirements', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repayment_schedule_type', models.CharField(choices=[('FIXED', 'Fixed Monthly'), ('HARVEST', 'Harvest-Based'), ('CUSTOM', 'Custom Schedule')], default='FIXED', max_length=20)),
                ('grace_period_days', models.IntegerField(default=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CropCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(choices=[('MAIZE', 'Maize'), ('BEANS', 'Beans'), ('RICE', 'Rice'), ('CASSAVA', 'Cassava'), ('POTATO', 'Potato'), ('COFFEE', 'Coffee'), ('TEA', 'Tea'), ('OTHER', 'Other')], max_length=20)),
                ('season', models.CharField(choices=[('SEASON_A', 'Season A (Sep-Feb)'), ('SEASON_B', 'Season B (Mar-Jun)'), ('SEASON_C', 'Season C (Jul-Aug)'), ('PERENNIAL', 'Perennial')], max_length=20)),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField()),
                ('farm_size_allocated', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estimated_yield', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('estimated_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_harvest_date', models.DateField(blank=True, null=True)),
                ('actual_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_cycles', to='farmers.farmer')),
            ],
            options={
                'ordering': ['-expected_harvest_date'],
            },
        ),
        migrations.CreateModel(
            name='HarvestBasedPaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_cycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_schedules', to='loans.cropcycle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HarvestPaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage_of_harvest', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='loans.harvestbasedpaymentschedule')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalYield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(choices=[('MAIZE', 'Maize'), ('BEANS', 'Beans'), ('RICE', 'Rice'), ('COFFEE', 'Coffee'), ('TEA', 'Tea'), ('OTHER', 'Other')], max_length=20)),
                ('season', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('yield_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('farm_size_used', models.DecimalField(decimal_places=2, max_digits=5)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_yields', to='farmers.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('DISBURSED', 'Disbursed'), ('ACTIVE', 'Active'), ('OVERDUE', 'Overdue'), ('PAID', 'Paid'), ('DEFAULTED', 'Defaulted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('disbursement_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('disbursement_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('credit_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('momo_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='farmers.farmer')),
                ('loan_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.loanproduct')),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
        migrations.AddField(
            model_name='harvestbasedpaymentschedule',
            name='loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_schedule', to='loans.loan'),
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_reference', models.CharField(max_length=100)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='loans.loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('USED', 'Used'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('expiry_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='loans.loan')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField()),
                ('due_date', models.DateTimeField()),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('PARTIALLY_PAID', 'Partially Paid')], default='PENDING', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedule', to='loans.loan')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loans.loantoken')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loans.approvedvendor')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('DISBURSEMENT', 'Loan Disbursement'), ('REPAYMENT', 'Loan Repayment')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('financial_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loans.loan')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_type', 'status'], name='loans_trans_transac_7ee9b3_idx')],
            },
        ),
    ]
